version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: 'root'
      MYSQL_HOST: 'localhost'
      MYSQL_DATABASE: 'flask-rest'
    volumes:
      - .:/app